spring:
  mail:
    host: ${EMAIL_SMTP_HOST} # smtp.gmail.com, smtp-mail.outlook.com, smtp.office365.com
    port: 465
    username: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          gitlab:
            authorization-uri: https://gitlab.remita.net/oauth/authorize
            token-uri: https://gitlab.remita.net/oauth/token
            user-info-uri: https://gitlab.remita.net/api/v4/user
            user-name-attribute: username
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "http://localhost:9095/login/oauth2/code/github"
            scope: user,repo
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:9095/login/oauth2/code/google"
            scope: profile,email
          gitlab:
            client-id: ${GITLAB_CLIENT_ID}
            client-secret: ${GITLAB_CLIENT_SECRET}
            redirect-uri: "http://localhost:9095/login/oauth2/code/gitlab"
            authorization-grant-type: authorization_code
            scope: read_user,api,read_api

secretString: "HFUKNSF09839IKSFV9348J39GHIUEWFJR9EF089WUJ4FNR9HG738UJW4ONEMSCO"